"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.payrolls = exports.departments = exports.holidays = exports.missPunchRequests = exports.userAttendance = exports.userLeaveRequests = exports.userleave = exports.jobs = exports.users = void 0;
var UserSchema_1 = require("./UserSchema");
Object.defineProperty(exports, "users", { enumerable: true, get: function () { return UserSchema_1.users; } });
var JobsSchema_1 = require("./JobsSchema");
Object.defineProperty(exports, "jobs", { enumerable: true, get: function () { return JobsSchema_1.jobs; } });
var UserLeaveSchema_1 = require("./UserLeaveSchema");
Object.defineProperty(exports, "userleave", { enumerable: true, get: function () { return UserLeaveSchema_1.userleave; } });
var UserLeaveReqSchama_1 = require("./UserLeaveReqSchama");
Object.defineProperty(exports, "userLeaveRequests", { enumerable: true, get: function () { return UserLeaveReqSchama_1.userLeaveRequests; } });
var AttendanceSchema_1 = require("./AttendanceSchema");
Object.defineProperty(exports, "userAttendance", { enumerable: true, get: function () { return AttendanceSchema_1.userAttendance; } });
var MissPunchRequests_1 = require("./MissPunchRequests");
Object.defineProperty(exports, "missPunchRequests", { enumerable: true, get: function () { return MissPunchRequests_1.missPunchRequests; } });
var HolidaysSchema_1 = require("./HolidaysSchema");
Object.defineProperty(exports, "holidays", { enumerable: true, get: function () { return HolidaysSchema_1.holidays; } });
var DepartmentSchema_1 = require("./DepartmentSchema");
Object.defineProperty(exports, "departments", { enumerable: true, get: function () { return DepartmentSchema_1.departments; } });
var PayrollSchema_1 = require("./PayrollSchema");
Object.defineProperty(exports, "payrolls", { enumerable: true, get: function () { return PayrollSchema_1.payrolls; } });
